apiVersion: v1
kind: Pod
metadata:
  name: visionserver
spec:
  hostIPC: true
  hostNetwork: true
  containers:
  - name: visionserver
    image: docker.io/fauzanhilmi/visionserver:latest
    ports:
    - containerPort: 8080
    env:
      - name: CUDA_MPS_LOG_DIRECTORY
        value: "/tmp/nvidia-log"
      - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
        value: "95" 
      - name: MODEL
        value: "alexnet"